name: ci

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: --max-old-space-size=6144

permissions: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Format check
        run: pnpm run format
      - name: Type check
        run: pnpm run type-check
      - name: Lint
        run: pnpm run lint
      - name: Build
        run: pnpm run build
